name: Build and Deploy

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create application.yml
        run: |
          mkdir -p ./src/main/resources
          cat > ./src/main/resources/application.yml << 'EOF'
          ${{ secrets.APPLICATION_YML }}
          EOF

#      - name: Create Firebase service account key
#        run: |
#          mkdir -p ./src/main/resources/firebase
#          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 }}" | base64 --decode > ./src/main/resources/firebase/serviceAccountKey.json
      - name: Create Apple key
        run: |
          mkdir -p ./src/main/resources/key
          cat << 'EOF' > ./src/main/resources/key/AuthKey.p8
          ${{ secrets.APPLE_KEY_BASE64 }}
          EOF

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew clean build

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.CONTAINER_NAME }}:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.CONTAINER_NAME }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH to server & deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 기존 컨테이너 중지 및 제거
            docker stop ${{ secrets.CONTAINER_NAME }} || true
            docker rm ${{ secrets.CONTAINER_NAME }} || true
            
            # 해당 이미지만 삭제 (다른 이미지에 영향 없음)
            docker rmi ${{ secrets.DOCKER_USERNAME }}/${{ secrets.CONTAINER_NAME }}:latest || true
            
            # Docker 이미지 Pull
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.CONTAINER_NAME }}:latest
            
            # Docker Network 생성 및 기존 컨테이너 연결
            docker network create walkit-network || true
            docker network connect walkit-network walkit-mysql || true

            docker run -d --name ${{ secrets.CONTAINER_NAME }} \
              --network walkit-network \
              -p 8080:8080 \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/${{ secrets.CONTAINER_NAME }}:latest